// `scalafmtConfigured*` (from ScalafmtConfigPlugin) and `scalafmtConfig` (from sbt-scalafmt)
// are auto-imported by enabling the plugins below — no explicit imports needed.

lazy val root = project
  .in(file("."))
  .enablePlugins(ScalafmtConfigPlugin)
  .settings(
    scalaVersion := "2.13.18",
    // Override the default version, and declare a few representative settings: a scalar, a
    // dotted/nested object and a list of rule names.
    scalafmtConfiguredVersion := "3.11.1",
    scalafmtConfiguredSettings := Map(
      "maxColumn" -> 100,
      "runner" -> Map("dialect" -> "scala213"),
      "rewrite" -> Map("rules" -> Seq("RedundantBraces", "RedundantParens")),
    ),
  )

// A project that enables the plugin but overrides nothing: it must still generate a valid config
// with the default version and no settings.
lazy val defaults = project
  .in(file("defaults"))
  .enablePlugins(ScalafmtConfigPlugin)
  .settings(
    scalaVersion := "2.13.18",
    // own file so it doesn't clobber the root project's .scalafmt.conf (both default to the
    // build's base directory).
    scalafmtConfiguredFile := baseDirectory.value / ".scalafmt.conf",
  )

// --- assertions, run from the `test` script ---

val checkFileExists = taskKey[Unit]("The generated config file exists with the expected name")
checkFileExists := {
  val f = scalafmtConfiguredFile.value
  assert(f.getName == ".scalafmt.conf", s"unexpected file name: ${f.getName}")
  assert(f.isFile, s"$f was not generated")
}

val checkContents = taskKey[Unit]("Generated file has the banner, version and configured settings")
checkContents := {
  val txt = IO.read(scalafmtConfiguredFile.value)
  assert(
    txt.contains("automatically generated by the sbt-scala-dotfiles-scalafmt plugin"),
    s"missing banner header in:\n$txt",
  )
  assert(txt.contains("version") && txt.contains("3.11.1"), s"missing version in:\n$txt")
  assert(txt.contains("maxColumn"), s"missing configured setting in:\n$txt")
  assert(txt.contains("RedundantBraces"), s"missing rewrite rule in:\n$txt")
}

val checkScalafmtWired = taskKey[Unit]("sbt-scalafmt's scalafmtConfig points at our generated file")
checkScalafmtWired := {
  val configured = scalafmtConfiguredFile.value
  val wired = scalafmtConfig.value
  assert(wired == configured, s"scalafmtConfig not wired: $wired (expected $configured)")
}

val checkDefaultsVersion =
  taskKey[Unit]("A project that overrides nothing renders the default version")
checkDefaultsVersion := {
  val txt = IO.read((defaults / scalafmtConfiguredFile).value)
  assert(txt.contains("3.10.0"), s"defaults project missing the default version:\n$txt")
}

val mutateConfig = taskKey[Unit]("Corrupt the generated config to force a staleness failure")
mutateConfig := {
  val f = scalafmtConfiguredFile.value
  IO.write(f, IO.read(f) + "\n# tampered\n")
}
