/*
 * Copyright 2026 Polyvariant
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.polyvariant.scaladotfiles

import com.typesafe.config.ConfigRenderOptions
import com.typesafe.config.ConfigValueFactory

/** Shared HOCON rendering used by both the scalafix and scalafmt config generators. Both tools are
  * configured with HOCON files, so the conversion of arbitrary Scala values to rendered HOCON lives
  * here once.
  *
  * Values may be any HOCON-representable shape: `String`, `Boolean`, numbers (`Int`/`Long`/
  * `Double`), `null`, `Seq[Any]` (lists), and nested `Map[String, Any]` (objects). They are handed
  * verbatim to the Typesafe config library, which renders them as HOCON.
  */
object HoconConfig {

  /** Banner prepended to every generated file, pointing back at the plugin that produced it (cf.
    * sbt-github-actions). The generated file is meant to be checked in, so this warns readers not
    * to edit it by hand.
    *
    * @param toolName
    *   the plugin name, e.g. `sbt-scala-dotfiles-scalafix`
    * @param keysDescription
    *   how to refer to the build keys, e.g. `scalafixConfigured*`
    * @param regenTask
    *   the sbt task that regenerates the file, e.g. `scalafixConfiguredGenerate`
    */
  def banner(toolName: String, keysDescription: String, regenTask: String): String =
    s"""# This file was automatically generated by the $toolName plugin.
       |# Do not edit by hand — change your build's $keysDescription keys instead
       |# and re-run $regenTask.
       |""".stripMargin

  private val renderOptions: ConfigRenderOptions =
    ConfigRenderOptions
      .defaults()
      .setJson(false) // HOCON-style output: unquoted keys, `=` assignment
      .setFormatted(true)
      .setOriginComments(false)
      .setComments(false)

  /** Recursively convert Scala collections to the Java collections that
    * [[ConfigValueFactory.fromAnyRef]] understands. Scalars pass through untouched.
    *
    * Built without `scala.jdk`/`JavaConverters` so the same source compiles cleanly on both Scala
    * 2.12 and 3.
    */
  private def toJava(value: Any): AnyRef =
    value match {
      case m: collection.Map[_, _] =>
        val out = new java.util.LinkedHashMap[String, AnyRef](m.size)
        m.foreach { case (k, v) => out.put(k.toString, toJava(v)) }
        out
      case xs: Iterable[_] =>
        val out = new java.util.ArrayList[AnyRef](xs.size)
        xs.foreach(v => out.add(toJava(v)))
        out
      case other => other.asInstanceOf[AnyRef]
    }

  /** Render a single value (typically a top-level `Map`) to its HOCON text. */
  def renderValue(value: Any): String =
    ConfigValueFactory.fromAnyRef(toJava(value)).render(renderOptions)

}
